# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51dfc21d7412a86e66caabd7bea023561bf989e43fbd6e0d478c847ec1bb1a9b9d7269db1ed99c766a957202bc3369bd1c50b58666b0c18e4bc5b2a0eda83f55

test:
  secret_key_base: 7e214be60925e33bfd6c6a3ab5d1738103c5fd23d357772e957c1b6c55cd50c350f764cf15a38112f418314e060d26269796639d5c5f056d00ba1bf095945f6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
